# Generated by Django 5.1.7 on 2025-10-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_pic'),
        ),
    ]
