# Generated by Django 5.1.7 on 2025-11-04 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(max_length=100)),
                ('renter_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
