# Generated by Django 5.1.7 on 2025-11-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discretion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
