# Generated by Django 5.1.7 on 2025-11-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_discretion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discretion',
            new_name='description',
        ),
    ]
